<link rel="stylesheet" href="css/main.css">
<?php include_once 'includes/nav.php'; ?>

<section class="sec-head" data-theme="bone">
  <div class="wrap">
    <div class="idx" data-i18n="legal.section">Legal</div>
    <h2 data-i18n-html="legal.conditions">Condiciones Generales de <em>Contratación</em></h2>
  </div>
</section>

<main class="wrap" style="padding:36px 0 80px">
  <style>
    .legal-card{
      max-width:900px;
      margin:24px auto;
      background:var(--paper);
      border:1px solid rgba(26,26,26,.06);
      padding:36px;
      border-radius:14px;
      box-shadow:0 16px 40px rgba(10,10,10,.06);
    }
    .legal-body{color:var(--ink-2);font-size:17px;line-height:1.9}
    .legal-body .lead{font-size:20px;color:var(--ash-2);margin-bottom:18px}
    .legal-body h2{margin-top:28px;font-size:20px;font-family:var(--display);color:var(--ink)}
    .legal-meta{font-family:var(--mono);font-size:13px;color:var(--ash);margin-bottom:14px}

    /* Legible content styles */
    .legal-content{max-width:64ch;margin:0 auto;color:var(--ink-2);font-size:17px;line-height:1.9}
    .legal-content h2{margin-top:1.4rem;font-size:1.125rem;font-family:var(--display);color:var(--ink)}
    .legal-content p{margin:0 0 1rem}
    .legal-content ul, .legal-content ol{margin-left:1.2em;margin-bottom:1rem}
    .legal-content li{margin:0.4rem 0}
    .legal-content .meta-note{font-size:13px;color:var(--ash)}

    @media (max-width:720px){
      .legal-body{font-size:18px}
      .legal-content{font-size:18px;padding:0 18px;max-width:100%}
    }
  </style>

      <div class="legal-card">
    <div class="legal-body">
      <div class="legal-meta">Documento original: condiciones.pdf</div>
      <div class="legal-content" data-i18n-html="legal.conditions_html">
<p>CONDICIONES GENERALES DE CONTRATACIÓN www.dynamic-tattoos.com Servicio Dynamic Tattoos. URL Dinámica para Códigos QR Las presentes Condiciones Generales de Contratación (en adelante, “CGC”) regulan la contratación de los servicios ofrecidos por Órbita Tecnológica Global S.L. a través del Sitio Web www.dynamic-tattoos.com. La contratación del servicio implica la aceptación plena, expresa e inequívoca de las presentes CGC en la versión publicada en el momento de la contratación.</p>

<p>1. IDENTIFICACIÓN DEL PRESTADOR</p>
<p>Denominación social Órbita Tecnológica Global S.L. CIF B42780791 Domicilio social Rúa Condesa Casa Barcena, 11, Vigo, España Registro Mercantil Registro Mercantil de Pontevedra, Tomo 4350, Folio 110, Hoja 67840 Correo electrónico info@dynamic-tattoos.com Sitio Web www.dynamic-tattoos.com</p>

<p>2. OBJETO DEL SERVICIO</p>
<p>Dynamic Tattoos presta un servicio de gestión de URL dinámica vinculada a un código QR diseñado para ser tatuado en la piel. El servicio permite al usuario actualizar el contenido digital asociado a dicho código QR (fotografías, vídeos o perfil completo) sin necesidad de modificar el tatuaje, siempre que mantenga activa la suscripción anual. La URL asignada al usuario tendrá el siguiente formato: qr-tatus.com/[código de 8 dígitos alfanuméricos]. Dynamic Tattoos garantiza que dicha URL permanecerá invariable durante la vigencia de la suscripción. El servicio tiene carácter exclusivamente digital. Dynamic Tattoos no interviene en ningún aspecto del proceso de tatuaje, cuya realización es responsabilidad única y exclusiva del usuario y del profesional del tatuaje que éste contrate.</p>

<p>3. MODALIDADES DE SERVICIO Y PRECIOS</p>
<p>Dynamic Tattoos ofrece las siguientes modalidades de suscripción anual: PAQUETE CONTENIDO PRECIO ANUAL IVA BÁSICO URL dinámica + perfil con 1 fotografía 4,90€/mes 58,80€/año Incluido PREMIUM URL dinámica + perfil con 1 vídeo 9,90€/mes 118,80€/año Incluido PREMIUM TOP URL dinámica + perfil completo (fotografías, vídeos y contenido múltiple) 19,90€/mes 238,80€/año Incluido</p>

<p>Los precios indicados incluyen el Impuesto sobre el Valor Añadido (IVA) aplicable. Dynamic Tattoos se reserva el derecho a modificar los precios vigentes, notificándolo al usuario con al menos treinta (30) días de antelación. El precio aplicable será el vigente en el momento de la contratación o renovación.</p>

<p>4. PROCESO DE CONTRATACIÓN</p>
<p>De conformidad con los artículos 97 a 99 del TRLGDCU y el artículo 27 de la LSSI-CE, el proceso de contratación se desarrolla mediante los siguientes pasos: 1. El usuario selecciona el paquete deseado y accede al formulario de registro. 2. El usuario facilita los datos necesarios para la creación de su cuenta y la gestión del pago. 3. El usuario revisa el resumen del pedido, el precio total con IVA y las presentes CGC. 4. El usuario acepta expresamente las CGC mediante la marca del casillero habilitado a tal efecto. La aceptación es requisito indispensable para completar la contratación. 5. El usuario selecciona la pasarela de pago habilitada en ese momento (Stripe, PayPal u otras que Dynamic Tattoos pueda incorporar en el futuro) y completa el abono de la cuota anual 6. Confirmado el pago, Dynamic Tattoos enviará al correo electrónico registrado una confirmación con los datos del servicio contratado y las credenciales de acceso al panel de gestión. Una vez dentro del panel, el usuario podrá configurar su perfil y, cuando lo estime oportuno, activar su URL dinámica y generar el código QR asociado. La activación del QR es una acción voluntaria del usuario y no se produce de forma automática tras el pago. El contrato se perfecciona en el momento en que el usuario recibe la confirmación del servicio por correo electrónico, conforme al artículo 1262 del Código Civil español.</p>

<p>5. DERECHO DE DESISTIMIENTO Y POLÍTICA DE NO REEMBOLSO</p>
<p>5.1 Excepción al derecho de desistimiento De conformidad con el artículo 103.a) del Texto Refundido de la Ley General para la Defensa de los Consumidores y Usuarios (TRLGDCU, aprobado por Real Decreto Legislativo 1/2007, de 16 de noviembre), el derecho de desistimiento de catorce (14) días naturales no será aplicable cuando el servicio contratado haya comenzado a ejecutarse con el previo consentimiento expreso del consumidor. A los efectos de las presentes CGC, el servicio se considera iniciado en el momento en que Dynamic Tattoos activa la URL dinámica personalizada y pone a disposición del usuario su panel de gestión y código QR asociado, hecho que se produce de forma inmediata tras la confirmación del pago. Desde ese momento, el usuario reconoce expresamente que el servicio digital ha comenzado su ejecución y renuncia al ejercicio del derecho de desistimiento, con independencia de si el código QR ha sido tatuado o no. Al completar la contratación, el usuario otorga su consentimiento expreso para que Dynamic Tattoos inicie la prestación del servicio de forma inmediata. A estos efectos, el servicio se considera iniciado en el momento en que Dynamic Tattoos activa el panel de gestión y pone a disposición del usuario sus credenciales de acceso, independientemente de si el usuario ha configurado su perfil, activado su URL dinámica o generado su código QR. El usuario reconoce expresamente que el acceso al panel de gestión constituye el inicio de la ejecución del servicio contratado, renunciando desde ese momento al ejercicio del derecho de desistimiento conforme al artículo 103.a) del TRLGDCU.</p>

<p>5.2 Política de no reembolso Dynamic Tattoos no efectuará devolución de las cuotas abonadas en ningún caso, incluyendo, a título enunciativo y no limitativo: • Cancelación voluntaria del servicio por el usuario antes del vencimiento de la suscripción anual. • Inactividad de la cuenta durante el período contratado. • Pérdida de legibilidad del código QR tatuado por causas ajenas a Dynamic Tattoos. • Cancelación por impago conforme al procedimiento establecido en la cláusula 7. Esta política es aplicable tanto a consumidores (B2C) como a usuarios empresariales (B2B).</p>

<p>6. OBLIGACIONES DE LAS PARTES</p>
<p>6.1 Obligaciones de Dynamic Tattoos • Activar la URL dinámica y entregar el código QR asociado en el plazo máximo de veinticuatro (24) horas desde la confirmación del pago. • Garantizar la disponibilidad de la URL dinámica durante la vigencia de la suscripción, salvo causas de fuerza mayor o mantenimiento técnico programado. • Notificar al usuario con al menos treinta (30) días de antelación cualquier modificación sustancial en las condiciones del servicio o en los precios. • Atender las solicitudes de soporte técnico remitidas a info@dynamic-tattoos.com en un plazo máximo de cuarenta y ocho (48) horas hábiles contadas desde la recepción de la solicitud, en días laborables de lunes a viernes. Dynamic Tattoos no garantiza tiempos de respuesta durante fines de semana y festivos, si bien realizará sus mejores esfuerzos para atender las incidencias críticas en el menor tiempo posible. • Tratar los datos personales del usuario de conformidad con la Política de Privacidad y la normativa vigente en materia de protección de datos.</p>

<p>6.2 Obligaciones del usuario • Facilitar datos veraces, actualizados y completos en el proceso de registro y contratación. • Abonar la cuota anual correspondiente en los plazos establecidos para mantener activo el servicio. • Utilizar el servicio de conformidad con la ley, la moral, las buenas costumbres y el orden público, así como con las presentes CGC. • No alojar en su perfil contenido ilícito, ofensivo, difamatorio, que vulnere derechos de terceros, que infrinja derechos de propiedad intelectual o industrial, o que pueda resultar perjudicial para Dynamic Tattoos o para terceros. • Garantizar que cuenta con los derechos de imagen y propiedad intelectual sobre el contenido multimedia subido a su perfil. • Notificar a Dynamic Tattoos cualquier uso no autorizado de su cuenta o acceso indebido al servicio.</p>

<p>7. DURACIÓN, RENOVACIÓN Y CANCELACIÓN DEL SERVICIO</p>
<p>7.1 Duración y renovación La suscripción tiene una duración de doce (12) meses desde la fecha de activación del servicio. Al término del período contratado, la suscripción podrá renovarse por períodos anuales sucesivos, previa notificación al usuario y confirmación del pago correspondiente. Dynamic Tattoos notificará al usuario la próxima fecha de vencimiento con una antelación mínima de treinta (30) días, mediante comunicación al correo electrónico registrado en la cuenta. 7.2 Cancelación por impago.  Procedimiento En caso de que el cargo automático no pueda ejecutarse en el método de pago registrado por causas imputables al usuario (tarjeta caducada, fondos insuficientes, bloqueo bancario u otras), Dynamic Tattoos aplicará el siguiente procedimiento: 1. Notificación de fallo de cobro : Dynamic Tattoos notificará al usuario por correo electrónico el fallo en el cargo automático, indicándole que debe actualizar su método de pago en el plazo de treinta (30) días naturales desde dicha comunicación 2. Suspensión temporal del servicio: Transcurrida la fecha de vencimiento sin que se haya efectuado el pago, Dynamic Tattoos suspenderá temporalmente el servicio, quedando la URL dinámica inactiva. El código QR tatuado dejará de ser funcional durante este período. 3. Período de gracia (2 meses): Durante los dos (2) meses siguientes a la suspensión, el usuario podrá regularizar el pago y reactivar el servicio. En este caso, la URL dinámica será restaurada en el plazo de veinticuatro (24) horas desde la confirmación del pago. 4. Baja definitiva: Transcurrido el período de gracia sin que se haya regularizado el pago, Dynamic Tattoos procederá a la baja definitiva de la cuenta y a la eliminación permanente de la URL dinámica y de todos los datos del perfil. El usuario reconoce y acepta expresamente que la baja definitiva implicará la inactivación permanente de la URL indexada al código QR tatuado, eximiendo a Dynamic Tattoos de cualquier responsabilidad por las consecuencias personales, estéticas o comerciales que ello pueda ocasionar. 7.3 Cancelación voluntaria por el usuario El usuario podrá cancelar su suscripción en cualquier momento a través de su cuenta o mediante comunicación a info@dynamic-tattoos.com. La cancelación surtirá efecto al término del período anual en curso, sin derecho a reembolso de la cuota abonada, conforme a la política establecida en la cláusula 5.2.</p>

<p>8. EXCLUSIÓN DE RESPONSABILIDAD POR EL PROCESO DE TATUAJE Dynamic Tattoos presta únicamente un servicio de carácter digital consistente en la gestión de URL dinámicas y el alojamiento de contenido en la nube. La Empresa no tiene relación alguna con el proceso de tatuaje, su ejecución, los materiales utilizados, la cualificación del profesional que lo realice, ni con cualquier consecuencia derivada del mismo. En particular, Dynamic Tattoos no será responsable en ningún caso por: • Errores técnicos cometidos por el tatuador en la reproducción del código QR que impidan o dificulten su lectura. • La pérdida de legibilidad del código QR como consecuencia de cambios físicos en la piel del usuario derivados del envejecimiento, cambios de peso, cicatrices, quemaduras, exposición solar u otras causas. • La utilización de tintas, técnicas de tatuaje o equipos inadecuados por parte del profesional del tatuaje. • Reacciones alérgicas, infecciones u otras consecuencias médicas derivadas del proceso de tatuaje. • La decisión del usuario de tatuarse el código QR, que es libre, voluntaria y bajo su exclusiva responsabilidad. El usuario, al contratar el servicio, declara conocer y aceptar que la funcionalidad del código QR depende tanto del correcto funcionamiento del servicio digital de Dynamic Tattoos como de la correcta ejecución del tatuaje por un profesional cualificado, siendo esta última condición ajena al control de Dynamic Tattoos.</p>

<p>9. TITULARIDAD DE LA CUENTA Y DEL PERFIL. GESTIÓN DE TERCEROS A los efectos de las presentes CGC, se distinguen las siguientes figuras: • Titular de la cuenta: persona física o jurídica que formaliza la contratación, abona la cuota anual y es el único interlocutor contractual con Dynamic Tattoos. • Titular del perfil: persona física cuyos datos personales e imagen aparecen en el perfil vinculado al código QR, que puede o no coincidir con el titular de la cuenta. En los supuestos en que el titular de la cuenta y el titular del perfil sean personas distintas, serán de aplicación las siguientes reglas: • Dynamic Tattoos rendirá cuentas exclusivamente al titular de la cuenta en materia de facturación, gestión del servicio y comunicaciones de carácter contractual. • Cualquier conflicto derivado de la relación entre el titular de la cuenta y el titular del perfil —incluyendo, sin carácter limitativo, disputas derivadas de la cancelación del servicio por decisión o impago del titular de la cuenta— será de exclusiva responsabilidad de las partes implicadas, conforme al artículo 1257 del Código Civil español. Dynamic Tattoos no tiene obligación de intervenir, mediar ni asumir responsabilidad alguna en dichos conflictos. • La cancelación del servicio por impago o por decisión del titular de la cuenta no otorga al titular del perfil derecho a exigir la continuidad del servicio frente a Dynamic Tattoos, sin perjuicio de las acciones legales que el titular del perfil pudiera ejercer frente al titular de la cuenta. • El titular del perfil conserva únicamente sus derechos como interesado en materia de protección de datos personales conforme al RGPD (acceso, rectificación, supresión, limitación, oposición y portabilidad), pudiendo ejercerlos directamente ante Dynamic Tattoos exclusivamente a efectos de la gestión de sus datos personales. El ejercicio de dichos derechos no otorga al titular del perfil ningún derecho contractual frente a Dynamic Tattoos , ni facultad alguna para exigir la continuidad, reactivación o mantenimiento del servicio, cuya gestión corresponde en exclusiva al titular de la cuenta</p>

<p>10. CONTENIDO DEL PERFIL. RESPONSABILIDAD DEL USUARIO El usuario es el único responsable del contenido que suba a su perfil. Dynamic Tattoos actúa como prestador de servicios de alojamiento en los términos del artículo 16 de la LSSI-CE, no siendo responsable del contenido almacenado salvo que tenga conocimiento efectivo de su carácter ilícito.</p>

<p>Queda expresamente prohibido alojar en el perfil: • Contenido que vulnere derechos de propiedad intelectual o industrial de terceros. • Contenido de carácter pornográfico, violento, discriminatorio o que atente contra la dignidad de las personas. • Datos personales de terceros sin su consentimiento expreso. • Contenido que pueda inducir a error o engaño a los usuarios que accedan al perfil mediante el código QR. • Cualquier contenido cuya publicación esté prohibida por la legislación aplicable. Dynamic Tattoos se reserva el derecho a suspender o eliminar, con efecto inmediato y sin previo aviso, cualquier perfil cuyo contenido incumpla las prohibiciones anteriores, sin que ello genere derecho a reembolso alguno. Esta facultad no implica obligación de supervisión activa del contenido alojado.</p>

<p>11. LIMITACIÓN DE RESPONSABILIDAD Dynamic Tattoos no garantiza la disponibilidad continua e ininterrumpida del Sitio Web ni del servicio. La Empresa no será responsable de los daños o perjuicios de cualquier naturaleza derivados de: • Interrupciones, fallos técnicos o desconexiones del servicio causados por circunstancias ajenas al control razonable de Dynamic Tattoos, incluyendo casos de fuerza mayor. • El uso indebido del servicio por parte del usuario. • Accesos no autorizados a la cuenta del usuario derivados de la negligencia de éste en la custodia de sus credenciales de acceso. • Daños derivados de virus informáticos u otros elementos dañinos introducidos por terceros, siempre que Dynamic Tattoos haya adoptado las medidas de seguridad razonables. • La inactivación del código QR tatuado como consecuencia de la cancelación del servicio por impago o por decisión del titular de la cuenta. En cualquier caso, la responsabilidad máxima de Dynamic Tattoos frente al usuario por cualquier concepto quedará limitada al importe de la cuota anual abonada por el usuario en el período de suscripción en que se haya producido el daño.</p>

<p>12. PROPIEDAD INTELECTUAL E INDUSTRIAL Todos los elementos del Sitio Web y de la plataforma de Dynamic Tattoos (incluyendo el diseño, código fuente, marcas, logotipos, textos, gráficos, interfaces, algoritmos de redirección dinámica, bases de datos y tecnología subyacente) son titularidad exclusiva de Órbita Tecnológica Global S.L. o de terceros que han autorizado legítimamente su uso, estando protegidos por la normativa española e internacional de propiedad intelectual e industrial, así como por la Ley 1/2019, de 20 de febrero, de Secretos Empresariales. Queda estrictamente prohibida la reproducción, copia o ingeniería inversa del modelo de redirección sin autorización expresa. El usuario conserva la titularidad sobre el contenido que suba a su perfil, otorgando a Dynamic Tattoos una licencia de uso limitada, no exclusiva, gratuita y revocable para alojar, reproducir y mostrar dicho contenido exclusivamente en el marco de la prestación del servicio contratado.</p>

<p>13. MODIFICACIÓN DE LAS CONDICIONES GENERALES Dynamic Tattoos se reserva el derecho a modificar las presentes CGC en cualquier momento. Las modificaciones serán notificadas al usuario con al menos treinta (30) días de antelación mediante comunicación al correo electrónico registrado y/o publicación en el Sitio Web. Si el usuario no acepta las nuevas condiciones, podrá resolver el contrato sin penalización alguna antes de la fecha de entrada en vigor de las modificaciones, sin derecho a reembolso de la cuota en curso conforme a la cláusula 5.2. La continuación en el uso del servicio tras la entrada en vigor de las modificaciones implicará la aceptación tácita de las nuevas condiciones.</p>

<p>14. LEGISLACIÓN APLICABLE Y JURISDICCIÓN</p>

<p>14.1 Legislación aplicable Las presentes CGC se rigen por la legislación española vigente. En particular, resultan de aplicación: • Real Decreto Legislativo 1/2007, de 16 de noviembre — Texto Refundido de la Ley General para la Defensa de los Consumidores y Usuarios (TRLGDCU). • Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE). • Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo (RGPD) y Ley Orgánica 3/2018, de 5 de diciembre (LOPDGDD). • Ley 1/2019, de 20 de febrero, de Secretos Empresariales. • Código Civil español y demás normativa civil y mercantil aplicable.</p>

<p>14.2 Jurisdicción y competencia Para la resolución de cualquier controversia derivada de las presentes CGC: • Clientes profesionales y empresas (B2B): las partes se someten expresamente a la jurisdicción exclusiva de los Juzgados y Tribunales de la ciudad de Vigo, España, con renuncia a cualquier otro fuero. • Consumidores finales (B2C): de conformidad con la normativa imperativa de consumo, cualquier litigio se someterá a los Juzgados y Tribunales del domicilio del consumidor o, en su caso, al lugar de cumplimiento de la obligación.</p>

<p>14.3 Resolución alternativa de litigios (ODR) En cumplimiento del artículo 14.1 del Reglamento (UE) 524/2013 sobre resolución de litigios en línea en materia de consumo, Dynamic Tattoos informa a los consumidores de que la Comisión Europea facilita una plataforma de resolución de litigios en línea, disponible en: https://ec.europa.eu/consumers/odr/</p>

<p>15. FECHA DE ACTUALIZACIÓN Las presentes Condiciones Generales de Contratación han sido actualizadas en mayo de 2026. Dynamic Tattoos se reserva el derecho a modificar su contenido, notificándolo al usuario conforme a lo establecido en la cláusula 13. Órbita Tecnológica Global S.L. — CIF: B42780791 — Vigo, España — info@dynamic-tattoos.com</p>

      </div>
    </div>
  </div>

</main>

<?php include_once 'includes/footer.php'; ?>
