<link rel="stylesheet" href="css/main.css">
<?php include_once 'includes/nav.php'; ?>

<section class="sec-head" data-theme="bone">
	<div class="wrap">
		<div class="idx">Legal</div>
		<h2>Política de <em>Privacidad</em></h2>
	</div>
</section>

<main class="wrap" style="padding:36px 0 80px">
	<style>
		.legal-card{
			max-width:900px;
			margin:24px auto;
			background:var(--paper);
			border:1px solid rgba(26,26,26,.06);
			padding:36px;
			border-radius:14px;
			box-shadow:0 16px 40px rgba(10,10,10,.06);
		}
		.legal-body{color:var(--ink-2);font-size:17px;line-height:1.9}
		.legal-body .lead{font-size:20px;color:var(--ash-2);margin-bottom:18px}
		.legal-body h2{margin-top:28px;font-size:20px;font-family:var(--display);color:var(--ink)}
		.legal-meta{font-family:var(--mono);font-size:13px;color:var(--ash);margin-bottom:14px}
		.muted{color:var(--ash);font-size:14px}

		/* Legible content styles */
		.legal-content{max-width:64ch;margin:0 auto;color:var(--ink-2);font-size:17px;line-height:1.9}
		.legal-content h2{margin-top:1.4rem;font-size:1.125rem;font-family:var(--display);color:var(--ink)}
		.legal-content p{margin:0 0 1rem}
		.legal-content ul, .legal-content ol{margin-left:1.2em;margin-bottom:1rem}
		.legal-content li{margin:0.4rem 0}
		.legal-content .meta-note{font-size:13px;color:var(--ash)}

		@media (max-width:720px){
			.legal-body{font-size:18px}
			.legal-content{font-size:18px;padding:0 18px;max-width:100%}
		}
	</style>

	<div class="legal-card">
		<div class="legal-body">
			<div class="legal-meta">Documento original: privacidad.pdf</div>
<div class="legal-content">
<p>POLÍTICA DE PRIVACIDAD www.dynamic-tattoos.com En cumplimiento del Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, General de Protección de Datos (RGPD), y de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y Garantía de los Derechos Digitales (LOPDGDD), Órbita Tecnológica Global S.L. informa a los usuarios de la presente Política de Privacidad sobre el tratamiento de sus datos personales. 1. RESPONSABLE DEL TRATAMIENTO Denominación social Órbita Tecnológica Global S.L. CIF B42780791 Domicilio social Rúa Condesa Casa Barcena, 11, Vigo, España Correo electrónico info@dynamic-tattoos.com Registro Mercantil Registro Mercantil de Pontevedra, Tomo 4350, Folio 110, Hoja 67840 2. DATOS PERSONALES QUE RECOGEMOS Dynamic Tattoos recopila las siguientes categorías de datos personales: 2.1 Datos facilitados directamente por el usuario (Art. 13 RGPD) • Datos de identificación: Nombre y apellidos. • Datos de contacto: Dirección de correo electrónico. • Datos de acceso: Nombre de usuario y contraseña (almacenada mediante algoritmos de cifrado hash unidireccional). • Datos de pago: Gestionados directamente por las pasarelas de pago Stripe y/o PayPal bajo entornos seguros SSL. Dynamic Tattoos no almacena, accede ni trata datos de tarjetas bancarias o cuentas corrientes. • Contenido del perfil: Fotografías, vídeos y demás material multimedia subido voluntariamente por el usuario a su perfil personal vinculado al código QR. El usuario garantiza que cuenta con los derechos de imagen y propiedad intelectual sobre dichos archivos. 2.2 Datos recogidos de forma automática • Datos de navegación: Dirección IP, tipo de navegador, sistema operativo, páginas visitadas y tiempo de permanencia. • Datos analíticos: Generados a través de Google Analytics 4 (GA4), cuya activación está supeditada a la obtención del consentimiento explícito del usuario. • Datos de cookies: Conforme a lo establecido en la Política de Cookies. 3. FINALIDADES DEL TRATAMIENTO Y BASES JURÍDICAS De conformidad con el artículo 13.1.c) del RGPD, se informa de las finalidades y bases jurídicas de cada tratamiento:</p>
<p>FINALIDAD BASE JURÍDICA PLAZO DE CONSERVACIÓN Gestión del registro y cuenta de usuario Ejecución del contrato — Art. 6.1.b) RGPD Vigencia de la relación contractual + 5 años Prestación del servicio de URL dinámica y perfil QR Ejecución del contrato — Art. 6.1.b) RGPD Vigencia de la suscripción + 3 meses tras baja definitiva Gestión del pago y facturación Ejecución del contrato + Obligación legal — Art. 6.1.b) y c) RGPD 6 años (Art. 30 Código de Comercio) Análisis web mediante Google Analytics 4 Consentimiento — Art. 6.1.a) RGPD 26 meses (según configuración GA4) Atención al cliente y gestión de consultas (chat en vivo) Interés legítimo — Art. 6.1.f) RGPD 1 año desde la última interacción Envío de comunicaciones comerciales (con consentimiento previo) Consentimiento — Art. 6.1.a) RGPD Hasta revocación del consentimiento 4. TITULARIDAD DEL PERFIL Y GESTIÓN DE CUENTAS DE TERCEROS Dynamic Tattoos distingue entre dos figuras con roles diferenciados en la relación contractual: • Titular de la cuenta: Persona física o jurídica que formaliza la contratación y abona la cuota correspondiente. Es el único interlocutor contractual con Dynamic Tattoos. • Titular del perfil: Persona física cuyos datos e imagen aparecen en el perfil vinculado al código QR tatuado, que puede o no coincidir con el titular de la cuenta. En los supuestos en que el titular de la cuenta y el titular del perfil sean personas distintas (por ejemplo, cuando una persona paga el servicio para otra), Dynamic Tattoos tratará los datos conforme a las siguientes reglas: • Dynamic Tattoos rendirá cuentas exclusivamente al titular de la cuenta en materia de facturación, gestión del servicio y comunicaciones contractuales. • El titular del perfil, en su condición de interesado a efectos del RGPD, conserva en todo caso sus derechos de protección de datos (acceso, rectificación, supresión, portabilidad, oposición y limitación del tratamiento), pudiendo ejercerlos directamente ante Dynamic Tattoos con independencia de quién pague el servicio. • Conforme al artículo 1257 del Código Civil español relativo a la eficacia de los contratos, cualquier conflicto derivado de la relación interna entre el titular de la cuenta y el titular del perfil será de exclusiva responsabilidad de las partes implicadas. Dynamic Tattoos no tiene obligación de intervenir, mediar ni asumir responsabilidad alguna en dichos conflictos. • La cancelación del servicio por impago o decisión del titular de la cuenta no otorga al titular del perfil derecho a exigir la continuidad del servicio frente a Dynamic Tattoos, sin perjuicio de las acciones que pudiera ejercer frente al titular de la cuenta. 5. DESTINATARIOS Y TRANSFERENCIAS INTERNACIONALES DE DATOS</p>
<p>5.1 Encargados del tratamiento (Art. 28 RGPD) Dynamic Tattoos utiliza los siguientes proveedores de servicios que actúan como encargados del tratamiento: PROVEEDOR FINALIDAD UBICACIÓN / GARANTÍA MÁS INFORMACIÓN Arsys Internet S.L. Alojamiento web y servidores España (UE) — Sin transferencia internacional www.arsys.es Stripe Technology Europe Ltd. Procesamiento de pagos Irlanda (UE) / EE.UU. — Data Privacy Framework (Decisión UE 2023/1795) stripe.com/es/privacy PayPal (Europe) S.à.r.l. et Cie, S.C.A. Procesamiento de pagos Luxemburgo (UE) / EE.UU. — Data Privacy Framework (Decisión UE 2023/1795) paypal.com/es/webapps/mpp/ua/privacy- full Google LLC (GA4) Análisis web y estadísticas EE.UU. — Data Privacy Framework (Decisión UE 2023/1795) policies.google.com/privacy Proveedor de chat en vivo (Debes agregarlo) Atención al cliente (colocar ubicación y garantía al tenerla) Agregar url Dynamic Tattoos no cederá sus datos personales a terceros ajenos a los indicados anteriormente, salvo obligación legal. 6. DERECHOS DE LOS INTERESADOS De conformidad con los artículos 15 a 22 del RGPD y los artículos 12 a 18 de la LOPDGDD, el usuario (así como el titular del perfil en su condición de interesado) tiene derecho a: • Derecho de acceso (Art. 15 RGPD): Obtener confirmación sobre si sus datos están siendo tratados y, en tal caso, acceder a los mismos y obtener información detallada sobre el tratamiento. • Derecho de rectificación (Art. 16 RGPD): Solicitar la rectificación de aquellos datos personales que sean inexactos o que se completen aquellos que estén incompletos. • Derecho de supresión / &quot;Derecho al olvido&quot; (Art. 17 RGPD): Solicitar la eliminación de sus datos personales cuando, entre otros motivos, estos ya no sean necesarios para los fines para los que fueron recabados. • Derecho de limitación del tratamiento (Art. 18 RGPD):  Solicitar la suspensión temporal o la restricción del tratamiento de sus datos en los supuestos legalmente previstos. • Derecho de portabilidad (Art. 20 RGPD): Recibir sus datos personales en un formato estructurado, de uso común y lectura mecánica, y transmitirlos a otro responsable del tratamiento. • Derecho de oposición (Art. 21 RGPD):  Oponerse en cualquier momento al tratamiento de sus datos, especialmente en lo relativo al envío de comunicaciones comerciales o por motivos basados en su situación particular.</p>
<p>• Derecho a retirar el consentimiento (Art. 7.3 RGPD):  Retirar el consentimiento otorgado en cualquier momento, sin que ello afecte a la licitud del tratamiento efectuado con anterioridad a su retirada. Procedimiento para el ejercicio de derechos:  Para ejercer cualquiera de los derechos descritos, el interesado podrá dirigir una comunicación por escrito al correo electrónico: info@dynamic-tattoos.com, indicando en el asunto “Derechos RGPD”. De conformidad con las directrices de las autoridades de control, Dynamic Tattoos solo requerirá una copia del documento oficial de identidad (DNI, NIE o Pasaporte) del solicitante en aquellos casos en que existan dudas razonables sobre su identidad y resulte estrictamente necesario para verificarla. Asimismo, el usuario queda informado de su derecho a presentar una reclamación ante la Agencia Española de Protección de Datos (AEPD)  si considera que el ejercicio de sus derechos no ha sido atendido satisfactoriamente, a través de su sede electrónica oficial: www.aepd.es. 7. MENORES DE EDAD El servicio de Dynamic Tattoos está dirigido exclusivamente a personas mayores de edad (18 años o la edad mínima legal en el país de residencia del usuario cuando sea superior). Por su propia naturaleza vinculada a la práctica del tatuaje, actividad que requiere mayoritariamente mayoría de edad, Dynamic Tattoos no recoge ni trata datos de menores de edad de forma intencionada. Si se tuviera conocimiento de que un menor ha facilitado datos personales sin el consentimiento de sus progenitores o tutores, se procederá a la supresión inmediata de dichos datos. 8. MEDIDAS DE SEGURIDAD Dynamic Tattoos ha adoptado las medidas técnicas y organizativas necesarias para garantizar la seguridad e integridad de los datos personales y evitar su alteración, pérdida, tratamiento o acceso no autorizado, habida cuenta del estado de la tecnología, la naturaleza de los datos almacenados y los riesgos a que están expuestos, conforme al artículo 32 del RGPD. Entre las medidas implementadas se incluyen: cifrado de contraseñas, protocolo HTTPS, control de accesos, copias de seguridad periódicas y alojamiento en servidores certificados ubicados en España (Arsys Internet S.L.). 9. COOKIES El Sitio Web utiliza cookies propias y de terceros. Para información detallada sobre el uso de cookies, tipos, finalidades y forma de gestionarlas, consulte nuestra Política de Cookies, disponible en el pie de página del Sitio Web. 10. ACTUALIZACIONES DE LA POLÍTICA DE PRIVACIDAD Dynamic Tattoos se reserva el derecho a modificar la presente Política de Privacidad para adaptarla a cambios legislativos, jurisprudenciales o de negocio. Las modificaciones serán notificadas al usuario mediante publicación en el Sitio Web y, cuando sean sustanciales, mediante comunicación al correo electrónico registrado. La presente Política de Privacidad ha sido actualizada en mayo de 2026.</p>
<p>Órbita Tecnológica Global S.L. — CIF: B42780791 — Vigo, España — info@dynamic-tattoos.com</p>
</div>
			</div>
	</div>

</main>

<?php include_once 'includes/footer.php'; ?>